
from pylivelinkface.pylivelinkface import FaceBlendShape


class BlendShapeConfig:
        # blend shape type, min and max value
        config = {
            FaceBlendShape.EyeBlinkLeft : (0.40, 0.70),
            # FaceBlendShape.EyeLookDownLeft : (-0.4, 0.0),
            # FaceBlendShape.EyeLookInLeft : (-0.4, 0.0),
            # FaceBlendShape.EyeLookOutLeft : (-0.4, 0.0),
            # FaceBlendShape.EyeLookUpLeft : (-0.4, 0.0),
            FaceBlendShape.EyeSquintLeft : (0.37, 0.44),
            FaceBlendShape.EyeWideLeft : (0.9, 1.2),
            FaceBlendShape.EyeBlinkRight : (0.40, 0.70),
            # FaceBlendShape.EyeLookDownRight : (-0.4, 0.0),
            # FaceBlendShape.EyeLookInRight : (-0.4, 0.0),
            # FaceBlendShape.EyeLookOutRight : (-0.4, 0.0),
            # FaceBlendShape.EyeLookUpRight : (-0.4, 0.0),
            FaceBlendShape.EyeSquintRight : (0.37, 0.44),
            FaceBlendShape.EyeWideRight : (0.9, 1.2),
            # FaceBlendShape.JawForward : (-0.4, 0.0),
            FaceBlendShape.JawLeft : (-0.4, 0.0),
            FaceBlendShape.JawRight : (0.0, 0.4),
            FaceBlendShape.JawOpen : (0.50, 0.55),
            FaceBlendShape.MouthClose : (3.0, 4.5),
            FaceBlendShape.MouthFunnel : (4.0, 4.8),
            FaceBlendShape.MouthPucker : (3.46, 4.92),
            FaceBlendShape.MouthLeft : (-3.4, -2.3),
            FaceBlendShape.MouthRight : ( 1.5, 3.0),
            FaceBlendShape.MouthSmileLeft : (-0.25, 0.0),
            FaceBlendShape.MouthSmileRight : (-0.25, 0.0),
            FaceBlendShape.MouthFrownLeft : (0.4, 0.9),
            FaceBlendShape.MouthFrownRight : (0.4, 0.9),
            # FaceBlendShape.MouthDimpleLeft : (-0.4, 0.0),
            # FaceBlendShape.MouthDimpleRight : (-0.4, 0.0),
            FaceBlendShape.MouthStretchLeft : (-0.4, 0.0),
            FaceBlendShape.MouthStretchRight : (-0.4, 0.0),
            FaceBlendShape.MouthRollLower : (0.4, 0.7),
            FaceBlendShape.MouthRollUpper : (0.31, 0.34),
            FaceBlendShape.MouthShrugLower : (1.9, 2.3),
            FaceBlendShape.MouthShrugUpper : (1.4, 2.4),
            FaceBlendShape.MouthPressLeft : (0.4, 0.5),
            FaceBlendShape.MouthPressRight : (0.4, 0.5),
            FaceBlendShape.MouthLowerDownLeft : (1.7, 2.1),
            FaceBlendShape.MouthLowerDownRight : (1.7, 2.1),
            # FaceBlendShape.MouthUpperUpLeft : (-0.4, 0.0),
            # FaceBlendShape.MouthUpperUpRight : (-0.4, 0.0),
            FaceBlendShape.BrowDownLeft : (1.0, 1.2),
            FaceBlendShape.BrowDownRight : (1.0, 1.2),
            FaceBlendShape.BrowInnerUp : (2.2, 2.6),
            FaceBlendShape.BrowOuterUpLeft : (1.25, 1.5),
            FaceBlendShape.BrowOuterUpRight : (1.25, 1.5),
            # FaceBlendShape.CheekPuff : (-0.4, 0.0),
            FaceBlendShape.CheekSquintLeft : (0.55, 0.63),
            FaceBlendShape.CheekSquintRight : (0.55, 0.63),
            # FaceBlendShape.NoseSneerLeft : (-0.4, 0.0),
            # FaceBlendShape.NoseSneerRight : (-0.4, 0.0),
            # FaceBlendShape.TongueOut : (-0.4, 0.0),
            # FaceBlendShape.HeadYaw : (-0.4, 0.0),
            # FaceBlendShape.HeadPitch : (-0.4, 0.0),
            # FaceBlendShape.HeadRoll : (-0.4, 0.0),
            # FaceBlendShape.LeftEyeYaw : (-0.4, 0.0),
            # FaceBlendShape.LeftEyePitch : (-0.4, 0.0),
            # FaceBlendShape.LeftEyeRoll : (-0.4, 0.0),
            # FaceBlendShape.RightEyeYaw : (-0.4, 0.0),
            # FaceBlendShape.RightEyePitch : (-0.4, 0.0),
            # FaceBlendShape.RightEyeRoll : (-0.4, 0.0), 
        }

       
